### ISSUE TITLE
您好，在使用自己的資料訓練時發生以下錯誤，請問我該如何解決..

### ISSUE THREAD

**Issue by JovanLCC** [audier/DeepSpeechRecognition#29]
Traceback (most recent call last):

  File "<ipython-input-1-4b0422afbd22>", line 1, in <module>
    runfile('C:/Users/Jovan/Desktop/speech_ex/DeepSpeechRecognition-master/DeepSpeechRecognition-master/train.py', wdir='C:/Users/Jovan/Desktop/speech_ex/DeepSpeechRecognition-master/DeepSpeechRecognition-master')

  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Jovan/Desktop/speech_ex/DeepSpeechRecognition-master/DeepSpeechRecognition-master/train.py", line 62, in <module>
    cost,_ = sess.run([lm.mean_loss,lm.train_op], feed_dict=feed)

  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 877, in run
    run_metadata_ptr)

  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1100, in _run
    feed_dict_tensor, options, run_metadata)

  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1272, in _do_run
    run_metadata)

  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1291, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: logits and labels must be broadcastable: logits_size=[80,2226] labels_size=[84,2226]
	 [[Node: softmax_cross_entropy_with_logits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](softmax_cross_entropy_with_logits/Reshape, softmax_cross_entropy_with_logits/Reshape_1)]]
	 [[Node: Adam/update/_224 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5228_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'softmax_cross_entropy_with_logits', defined at:
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 241, in <module>
    main()
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 237, in main
    kernel.start()
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2808, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-4b0422afbd22>", line 1, in <module>
    runfile('C:/Users/Jovan/Desktop/speech_ex/DeepSpeechRecognition-master/DeepSpeechRecognition-master/train.py', wdir='C:/Users/Jovan/Desktop/speech_ex/DeepSpeechRecognition-master/DeepSpeechRecognition-master')
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/Jovan/Desktop/speech_ex/DeepSpeechRecognition-master/DeepSpeechRecognition-master/train.py", line 40, in <module>
    lm = Lm(lm_args)
  File "C:\Users\Jovan\Desktop\speech_ex\DeepSpeechRecognition-master\DeepSpeechRecognition-master\model_language\transformer.py", line 324, in __init__
    self.loss = tf.nn.softmax_cross_entropy_with_logits_v2(logits=self.logits, labels=self.y_smoothed)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\nn_ops.py", line 1879, in softmax_cross_entropy_with_logits_v2
    precise_logits, labels, name=name)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_nn_ops.py", line 7209, in softmax_cross_entropy_with_logits
    name=name)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
    op_def=op_def)
  File "C:\Users\Jovan\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): logits and labels must be broadcastable: logits_size=[80,2226] labels_size=[84,2226]
	 [[Node: softmax_cross_entropy_with_logits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](softmax_cross_entropy_with_logits/Reshape, softmax_cross_entropy_with_logits/Reshape_1)]]
	 [[Node: Adam/update/_224 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5228_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
===============================================================
![image](https://user-images.githubusercontent.com/31316865/50549228-3c6d4d00-0c94-11e9-850f-8ba399cba066.png)

**Comment by audier** [comment]
应该是使用的数据不一致导致的
是不是使用了部分数据，词典部分生成需要使用全部数据来生成vocab，然而你生成的一个是80，一个是84
