### ISSUE TITLE
求助：训练错误

### ISSUE THREAD

**Issue by YasinZhao** [audier/DeepSpeechRecognition#37]
作者大大，你好，在学习你的代码时，按照你给定的配置自己训练时，出现如下错误，可否帮忙看下是什么导致的，谢谢~
this is the 1 th epochs trainning !!!
WARNING:tensorflow:Variable *= will be deprecated. Use variable.assign_mul if you want assignment to the variable value or 'x = x * y' if you want a new python Tensor object.
Epoch 1/1
2019-01-16 15:20:50.844418: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at strided_slice_op.cc:105 : Invalid argument: slice index 0 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds.
	 [[Node: ctc/scan/TensorArrayUnstack/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ctc/scan/TensorArrayUnstack/Shape/_707, batch_normalization_1/strided_slice/stack, batch_normalization_1/strided_slice/stack_1, batch_normalization_1/strided_slice/stack_1)]]
	 [[Node: training/Adam/gradients/batch_normalization_7/cond/batchnorm/mul_1_grad/Shape/_567 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_956_t...grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 29, in <module>
    am.ctc_model.fit_generator(batch, steps_per_epoch=batch_num, epochs=1)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2224, in fit_generator
    class_weight=class_weight)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1883, in train_on_batch
    outputs = self.train_function(ins)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2478, in __call__
    **self.session_kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 0 of dimension 0 out of bounds.
	 [[Node: ctc/scan/TensorArrayUnstack/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ctc/scan/TensorArrayUnstack/Shape/_707, batch_normalization_1/strided_slice/stack, batch_normalization_1/strided_slice/stack_1, batch_normalization_1/strided_slice/stack_1)]]
	 [[Node: training/Adam/gradients/batch_normalization_7/cond/batchnorm/mul_1_grad/Shape/_567 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_956_t...grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'ctc/scan/TensorArrayUnstack/strided_slice', defined at:
  File "train.py", line 17, in <module>
    am = Am(am_args)
  File "/home/zy/DeepSpeechRecognition/model_speech/cnn_ctc.py", line 31, in __init__
    self._ctc_init()
  File "/home/zy/DeepSpeechRecognition/model_speech/cnn_ctc.py", line 55, in _ctc_init
    ([self.labels, self.outputs, self.input_length, self.label_length])
  File "/root/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/layers/core.py", line 663, in call
    return self.function(inputs, **arguments)
  File "/home/zy/DeepSpeechRecognition/model_speech/cnn_ctc.py", line 101, in ctc_lambda
    return K.ctc_batch_cost(labels, y_pred, input_length, label_length)
  File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3944, in ctc_batch_cost
    sparse_labels = tf.to_int32(ctc_label_dense_to_sparse(y_true, label_length))
  File "/root/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 3908, in ctc_label_dense_to_sparse
    initializer=init, parallel_iterations=1)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 579, in scan
    elem_ta.unstack(elem) for elem_ta, elem in zip(elems_ta, elems_flat)]
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/functional_ops.py", line 579, in <listcomp>
    elem_ta.unstack(elem) for elem_ta, elem in zip(elems_ta, elems_flat)]
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 944, in unstack
    return self._implementation.unstack(value, name=name)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 118, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 331, in unstack
    num_elements = array_ops.shape(value)[0]
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 597, in _slice_helper
    name=name)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 763, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8148, in strided_slice
    name=name)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): slice index 0 of dimension 0 out of bounds.
	 [[Node: ctc/scan/TensorArrayUnstack/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](ctc/scan/TensorArrayUnstack/Shape/_707, batch_normalization_1/strided_slice/stack, batch_normalization_1/strided_slice/stack_1, batch_normalization_1/strided_slice/stack_1)]]
	 [[Node: training/Adam/gradients/batch_normalization_7/cond/batchnorm/mul_1_grad/Shape/_567 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_956_t...grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by audier** [comment]
你好，确认一下训练之前有没有将原来的模型删除呢

**Comment by audier** [comment]
在logs_am和logs_lm中的模型都要删除

**Comment by YasinZhao** [comment]
我又重新试了一下，当清空logs_am、logs_lm两个文件中的所有模型后，batch_size=1时依然报上述错误，改为10时可以正常运行，还是有点懵，这个会是什么原因？

**Comment by audier** [comment]
你好，我还是怀疑是因为模型维度不匹配导致的。
一旦开始训练，请务必保证train_data不会改变。或者保证输出的vocab不会有新的标签引入。

**Comment by YasinZhao** [comment]
好的，谢谢，我再仔细检查下~

**Comment by audier** [comment]
@YasinZhao 你好，解决了吗

**Comment by YasinZhao** [comment]
嗯嗯，已经解决了，确实是模型维度不匹配导致的，忘记上来告诉你一声了，还劳烦你过问，非常感谢~~
