### ISSUE TITLE
Dimension 1 in both shapes must be equal,

### ISSUE THREAD

**Issue by KiAlexander** [audier/DeepSpeechRecognition#46]
_________________________________________________________________
load acoustic model...
Traceback (most recent call last):
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 686, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 1249 and 230 for 'Assign_62' (op: 'Assign') with input shapes: [256,1249], [256,230].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 47, in <module>
    am.ctc_model.load_weights('logs_am/model.h5')
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 2622, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/engine/topology.py", line 3143, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 2247, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 573, in assign
    return state_ops.assign(self._variable, value, use_locking=use_locking)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/home/yjm/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 1 in both shapes must be equal, but are 1249 and 230 for 'Assign_62' (op: 'Assign') with input shapes: [256,1249], [256,230].

train.py is modified as the following:
 # 0.准备训练所需数据------------------------------
 data_args = data_hparams()
 data_args.data_type = 'train'
 data_args.data_path = 'data/'
 data_args.thchs30 = True
 data_args.aishell = True
 data_args.prime = False
 data_args.stcmd = True
 data_args.batch_size = 1
 #data_args.data_length = 10
 data_args.data_length = None
 data_args.shuffle = True
 train_data = get_data(data_args)

 # 0.准备验证所需数据------------------------------
 data_args = data_hparams()
 data_args.data_type = 'dev'
 data_args.data_path = 'data/'
 data_args.thchs30 = True
 data_args.aishell = True
 data_args.prime = False
 data_args.stcmd = True
 data_args.batch_size = 1
 data_args.data_length = None
 #data_args.data_length = 10
 data_args.shuffle = True
 dev_data = get_data(data_args)

**Comment by madeirak** [comment]
我猜你用的是代码里带的模型，data_length需设置为10即可，除非你改为None后，自己训练模型，再进行测试
