### ISSUE TITLE
 python3 train.py 报错　KeyError: 'val_acc'

### ISSUE THREAD

**Issue by yangy4444** [audier/DeepSpeechRecognition#48]

**Comment by yangy4444** [comment]
_________________________________________________________________
Epoch 1/10
2/2 [==============================] - 18s 9s/step - loss: 550.3453 - val_loss: 245.8563
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    am.ctc_model.fit_generator(batch, steps_per_epoch=batch_num, epochs=10, callbacks=[checkpoint], workers=1, use_multiprocessing=False, validation_data=dev_batch, validation_steps=200)
  File "/usr/local/lib/python3.5/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python3.5/dist-packages/keras/callbacks.py", line 429, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_acc'

**Comment by madeirak** [comment]
把val_acc换成val_loss试试

**Comment by wangmengtian** [comment]
> 在cnn_ctc.py的模型编译里添加metrics = ['accuracy']就好了

请问具体在什么位置加呢？

**Comment by wangmengtian** [comment]
> 在cnn_ctc.py的模型编译里添加metrics = ['accuracy']就好了

楼上正解，感谢！Google的时候找到了类似问题和解法
[链接](https://github.com/keras-team/keras/issues/6104#issuecomment-290945569)

**Comment by guker** [comment]
> > 在cnn_ctc.py的模型编译里添加metrics = ['accuracy']就好了
> 
> 楼上正解，感谢！Google的时候找到了类似问题和解法
> [keras-team/keras#6104 (comment)](https://github.com/keras-team/keras/issues/6104#issuecomment-290945569)

thank you， it works.

**Comment by l695290718** [comment]
这个回答是不是有问题？出现KeyError: 'val_acc'时，检查model.fit() 有没有添加validation_split参数

**Comment by qingge545** [comment]
是的，官方文档指出，在指定验证集的时候，在on_epoch_end回调中的logs才会包含'val_acc'参数。model.fit()添加上述参数，会指定验证集。
