### ISSUE TITLE
使用prime和stcmd后（数据集全开）语言模型训练报错

### ISSUE THREAD

**Issue by chen1399** [audier/DeepSpeechRecognition#98]
四个数据集全用，data_length=None，训练时报错
`
2019-08-14 11:32:27.969447: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPe: 1, name: GeForce RTX 2080 Ti, pci bus id: 0000:42:00.0, compute capability: 7.5)
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    input_batch, label_batch = next(batch)
  File "/home/user/DeepSpeechRecognition-master/utils.py", line 128, in get_lm_batch
    [self.han2id(line, self.han_vocab) + [0] * (max_len - len(line)) for line in label_batch])
  File "/home/user/DeepSpeechRecognition-master/utils.py", line 128, in <listcomp>
    [self.han2id(line, self.han_vocab) + [0] * (max_len - len(line)) for line in label_batch])
  File "/home/user/DeepSpeechRecognition-master/utils.py", line 135, in han2id
    return [vocab.index(han) for han in line]
  File "/home/user/DeepSpeechRecognition-master/utils.py", line 135, in <listcomp>
    return [vocab.index(han) for han in line]
ValueError: ' ' is not in list
`
数据长度设为10就没什么问题

**Comment by chen1399** [comment]
语言模型报错，声学模型没问题

**Comment by XinyuDu** [comment]
请问有解决方案么？
